apiVersion: v2
name: try-helm-cass-operator
description: A composite Helm chart that includes the cass-operator helm chart and monitoring

type: application

version: 0.1.0

appVersion: 1.16.0

dependencies:
  - name: kube-prometheus-stack
    version: "9.4.*"
    repository: https://prometheus-community.github.io/helm-charts
  - name: cass-operator
    version: "1.4.*"
    repository: https://datastax.github.io/charts
