apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{.Release.Name}}-actuator
  namespace: {{.Release.Namespace}}
  labels:
    release: {{.Release.Name}}
spec:
  namespaceSelector:
    matchNames:
      - {{.Release.Namespace}}
  selector:
    matchLabels:
      prometheus/scrape-type: actuator
  podMetricsEndpoints:
    - port: actuator
      path: /actuator/prometheus