apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "deploy-ceres-gke.cassandraStorageClassName" .}}
  namespace: {{.Release.Namespace}}
provisioner: kubernetes.io/gce-pd
parameters:
  type: {{.Values.cassandra.storageClassType}}
  replication-type: none
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true